version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres_rh
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rh_db_connect
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rh_db_connect"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/rh_db_connect
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./import_data.py:/app/import_data.py
      - ./db_rh_connect.py:/app/db_rh_connect.py

volumes:
  postgres_data:
